# 使用一个基础镜像作为起点
FROM 172.30.41.248/base_images/python:3.11.3

# 设置工作目录
WORKDIR /app

# 复制当前目录的所有文件到容器中
COPY . /app

# 安装ansible(如果不适用ansible则不需要安装)
RUN pip install ansible -i https://pypi.tuna.tsinghua.edu.cn/simple/

# 安装依赖（因为下载依赖需要外网，所以把下载依赖放到启动的时候去执行，因为启动的时候添加外网依赖）
#RUN pip install --no-cache-dir -r requirements/requirements.txt
#RUN pip --default-timeout=100 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn -r /app/requirements/requirements.txt

# 定义容器启动时执行的命令
#CMD ["python", "/app/main_v3.py"]

CMD ["/bin/sh", "/app/server_startup.sh"]